title: Het Pandya
description: >- 
  Hi I am Het, passionate about taking dives into the ocean of Machine Learning, explore and solve real world problems with Computer Vision and Natural Language Processing.

image: /images/about-2.jpg

url: https://hetpandya.github.io/

keywords: het,pandya,het pandya,machine learning engineer,data scientist